<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newseditrestriction"
 *
 * Auto generated by Extension Builder 2014-05-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'News Edit Restriction',
	'description' => 'TYPO3 extension to restrict editing of EXT:news records to users having rights to their categories',
	'category' => 'be',
	'author' => 'Lorenz Ulrich',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'news' => '2.3.0-3.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);